# Generated by Django 4.1.7 on 2023-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ten',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='app.dienthoai'),
        ),
    ]
