# Generated by Django 4.1.7 on 2023-03-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cart_gia_remove_cart_image_remove_cart_ten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, null=True)),
                ('soluong', models.IntegerField()),
                ('gia', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
