# Generated by Django 4.1.7 on 2023-03-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_listcart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='app.dienthoai'),
        ),
    ]
