# Generated by Django 4.1.7 on 2023-03-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_cart1_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ten',
        ),
    ]
