# Generated by Django 4.1.7 on 2023-03-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ten',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
