# Generated by Django 4.1.7 on 2023-03-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cart_ten'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart1',
        ),
    ]
